### ISSUE TITLE
Some valid Hex colors are not parsed into RGB

### ISSUE THREAD

**Issue by hfloyd** [abjerner/Skybrud.Colors#5] opened 2024-03-05 21:13 UTC
Hi!

So, I noticed while using the `ColorUtils.HexToRgb()` function that often I am getting back a NULL color, when the value is a valid (HTML-displaying) Hex color (https://www.colorhexa.com/a58d42).  Stepping through the source code, for one such color, I see that the failure is happening in a RegEx function - it doesn't match any of the three possible RegEx expressions:

![image](https://github.com/abjerner/Skybrud.Colors/assets/1252593/3af85cb4-4e28-4a1b-b9cc-7487ecd376e7)

There were several colors I was using which were returning NULL (including #ECF1F4 and #A9B3BA)

My skill with Regex is mediocre, and I'm not entirely sure what the strategy is with your RegEx, so I looked for a solution to how others might convert HEX colors, and came across this: https://stackoverflow.com/a/74679005/3841490 

When I added a final conversion attempt to the code:

```
...
    if (RegexPatterns.Hex3.IsMatch(input, out r, out g, out b, out byte alpha)) {
        result = new RgbColor(r, g, b, alpha / 255d);
        return true;
    }

    //Else try this
    try {
        int rgbInt = Convert.ToInt32(input, 16);
        byte red = (byte)((rgbInt >> 16) & 255);
        byte green= (byte)((rgbInt >> 8) & 255);
        byte blue = (byte)(rgbInt & 255);
        result = new RgbColor(red, green, blue);
        return true;
    
    } catch (Exception e) {
       //skip
    }

    return false;
}
```
All of the colors were returning an RgbColor.

If you want me to put in a PR I can, or feel free to integrate a fall-back like this yourself, or perhaps you know why those colors weren't matching a RegEx?

**Comment by abjerner** [comment] 2024-03-05 22:05
Hi @hfloyd and thanks for reporting this 👍 

I haven't really been using this package a lot in the few last years, which must be why I haven't encountered this my self. The problem is a bit silly to be honest (from my part).

The REGEX patterns for the HEX codes only check for `a-f`, but not `A-F`. This would be fine if I had added the `IgnoreCase` flag, but as you can see from the screenshot below, I've missed that part 🤦‍♂️ 

![image](https://github.com/abjerner/Skybrud.Colors/assets/3634580/fc29152b-16d0-4529-ba2e-f513362e52cc)

I think if the `IgnoreCase` flag is added, it should work fine. I will try to test this a bit 😉 

The reason for the three HEX patterns is that there is the normal six digit format, but then there is also the three digit shorthand (eg. `#fff`) as well as the eight digit format including the alpha level.

**Comment by hfloyd** [comment] 2024-03-06 16:17
Yep, that fixes it! I'll put in a PR for you.

**Comment by abjerner** [comment] 2024-03-06 16:35
I've now merged #6, so a I'll have a new release out soon 😉 

I had a few minutes before heading home from work, so I worked a bit on improving my unit tests. It turns out  that the `ColorUtils.TryParse` method has worked fine since it calls `ToLower()` before continuing with the parsing, while `ColorUtils.HexToRgb` doesn't hence your experience null values.

With the REGEX flags updated, I should be able to remove the `ToLower()` as it should now be redundant. I'll play bit more around with this and updating the unit tests, and then push a new release.

Thanks for your help again 👍

**Comment by hfloyd** [comment] 2024-03-06 16:48
My pleasure! Have a great evening!

**Comment by abjerner** [comment] 2024-03-06 18:20
@hfloyd you too 😉 

A new release is now out with the fix: https://github.com/abjerner/Skybrud.Colors/releases/tag/v1.1.1

Not that there is a lot of documentation yet, but you can now find a bit of documentation for **Skybrud.Colors** on our new documentation site: https://packages.limbo.works/skybrud.colors/docs/

**Closed as completed by abjerner** 2024-03-06 18:20 UTC
